steps:
    - id: terraform init
      name: "hashicorp/terraform:$_TF_VERSION"
      entrypoint: "sh"
      args:
          - "-c"
          - |
              cd terraform/
              terraform init -backend-config="bucket=ysance-eatsupdata-1-gcs-terraform-backend-eu-dv" -backend-config="prefix=ysance-eatsupdata-1"

    - id: terraform apply
      name: "hashicorp/terraform:$_TF_VERSION"
      entrypoint: "sh"
      args:
          - "-c"
          - |
              cd terraform/
              terraform apply -auto-approve -var-file=variables_$_ENV.tfvars -lock=false
